Multi-tenancy work in progress
- Pull in roadmap-extension code. To run you will now need to supply a GitHub access token in the form  GITHUB_TOKEN=x-access-token<token> before running any compose commands. You can export this variable to run it only once if required.
- Added Gemfile.custom.  This is used to get the roadmap-extension code.  Note that the environment variable ROADMAP_EXTENSION_VERSION can be passed in/set via the compose file and ordinarily would be interpolate in the gem file.  I’ve commented this out for the timebeing as it wasn’t working - I suspect it requires a git tag in the extension repo.
- Added script precompile assets as start puma.  Not possible to precompile assets during build stage as db container is not available.  Solution for now is to do it when we start the container
- .env file now only contains parameters required for the pre-processing stage
- Added dmp_app and dmp_web targets to the compose file.  Also tidied up build args so they can be defined in the environment (or .env file) and sensible defaults are supplied where appropriate.
- Modified app Dockerfile attempting to get multi-tenancy working. Currently failing with /opt/src/dmp/app/mailers/user_mailer.rb:6:in `<class:UserMailer>': undefined method `[]' for nil:NilClass (NoMethodError)